# Generated by Django 3.2.4 on 2022-05-31 13:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('underwearshop', '0015_deleting_log_entries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productremains',
            name='price',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Price'),
        ),
    ]
