# Generated by Django 3.2.4 on 2022-05-31 13:54

from django.db import migrations


def convert_to_dollar(apps, schema_editor):

    ProductRemains = apps.get_model('underwearshop', 'ProductRemains')
    remains = ProductRemains.objects.all()
    for remain in remains:
        remain.price = round(remain.price / 39, 2)
    ProductRemains.objects.bulk_update(remains, ['price'])


def convert_to_hryvnia(apps, schema_editor):

    ProductRemains = apps.get_model('underwearshop', 'ProductRemains')
    remains = ProductRemains.objects.all()
    for remain in remains:
        remain.price = remain.price * 39
    ProductRemains.objects.bulk_update(remains, ['price'])


class Migration(migrations.Migration):

    dependencies = [
        ('underwearshop', '0016_alter_productremains_price'),
    ]

    operations = [
        migrations.RunPython(
            convert_to_dollar, reverse_code=convert_to_hryvnia
        )
    ]
