# Generated by Django 3.2.4 on 2022-04-05 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('underwearshop', '0019_switching_images_to_json'),
    ]

    operations = [
        migrations.DeleteModel(name='ProductImage', ),
    ]
