# Generated by Django 3.2.4 on 2022-06-23 07:07

from django.db import migrations
from django.core import management


def update_translation_fields(apps, schema_editor):

    management.call_command("update_translation_fields", "underwearshop")

class Migration(migrations.Migration):

    dependencies = [
        ('underwearshop', '0021_create_translation_fields_0848'),
    ]

    operations = [
        migrations.RunPython(
            update_translation_fields,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
